In [3]:
import pandas as pd
import numpy as np


import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

In [5]:
data={"height":[185,179,168,179,192,188,180,180,183,180,180,177],
      "weight":[72,56,60,68,72,77,71,70,84,88,67,76]}

In [ ]:
initial_centroid=np.array([
    [185,72],
    [176,56]
])

In [ ]:
kmesns=KMeans(
    n_clusters=2,
    init=initial_centroid,
    n_init=1,
    random_state=42
)

In [9]:
KMeans.fit(df)

AttributeError: 'DataFrame' object has no attribute '_validate_params'

In [ ]:
KMeans(init=array([[185,72],
                   [170,56]]),n_clusters=)

In [6]:
df=pd.DataFrame(data)
df

    height  weight
0      185      72
1      179      56
2      168      60
3      179      68
4      192      72
5      188      77
6      180      71
7      180      70
8      183      84
9      180      88
10     180      67
11     177      76

In [10]:
df

    height  weight
0      185      72
1      179      56
2      168      60
3      179      68
4      192      72
5      188      77
6      180      71
7      180      70
8      183      84
9      180      88
10     180      67
11     177      76

In [11]:
df.shape

(12, 2)