In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [3]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [4]:
df = sns.load_dataset('flights')
df.head()

   year month  passengers
0  1949   Jan         112
1  1949   Feb         118
2  1949   Mar         132
3  1949   Apr         129
4  1949   May         121

In [5]:
months= {
    "Jan": 1,
    "feb": 2,
    "Mar": 3,
    "Apr": 4,
    "May": 5,
    "Jun": 6,
    "Jul": 7,
    "Aug": 8,
    "Sep": 9,
    "Oct": 10,
    "Nov": 11,
    "Dec": 12,
}

df["month"] = df["month"].map(months)

In [6]:
x= df[["year","month"]]
y= df["passengers"]

In [7]:
# Step 3: Train aur test data mein split karo
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

In [8]:
x_test

     year  month
117  1958   10.0
19   1950    8.0
82   1955   11.0
97   1957    NaN
56   1953    9.0
12   1950    1.0
132  1960    1.0
65   1954    6.0
66   1954    7.0
18   1950    7.0
51   1953    4.0
78   1955    7.0
94   1956   11.0
133  1960    NaN
100  1957    5.0
64   1954    5.0
27   1951    4.0
69   1954   10.0
125  1959    6.0
73   1955    NaN
11   1949   12.0
119  1958   12.0
110  1958    3.0
113  1958    6.0
55   1953    8.0
45   1952   10.0
9    1949   10.0
4    1949    5.0
26   1951    3.0

In [9]:
print(df.isnull().sum())

year           0
month         12
passengers     0
dtype: int64

In [10]:
print(x.isnull().sum())

year      0
month    12
dtype: int64

In [11]:
df = df.dropna()

In [12]:
# Step 3: Train aur test data mein split karo
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

In [13]:
# model=LinearRegression()
# model.fit(x_train, y_train)
# y_pred = model.predict(x_test)
print(x_train.isnull().sum())
print(y_train.isnull().sum())

year     0
month    9
dtype: int64
0

In [14]:
# y_pred=model.predict()
df["month"] = df["month"].fillna(df["month"].mean())

In [15]:
month = {
    "jan": 1,
    "feb": 2,
    "mar": 3,
    "apr": 4,
    "may": 5,
    "jun": 6,
    "jul": 7,
    "aug": 8,
    "sep": 9,
    "oct": 10,
    "nov": 11,
    "dec": 12,
}

In [16]:
# Step 3: Train aur test data mein split karo
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

In [17]:
# model = LinearRegression()
# model.fit(x_train, y_train)
print(df.isnull().sum())

year          0
month         0
passengers    0
dtype: int64

In [18]:
print(x.isnull().sum())

year      0
month    12
dtype: int64

In [19]:
x = df[["year", "month"]]
y = df["passengers"]

In [20]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [21]:
print(df.shape)
print(x.shape)
print(y.shape)
print(df.head())

(132, 3)
(132, 2)
(132,)
   year  month  passengers
0  1949    1.0         112
2  1949    3.0         132
3  1949    4.0         129
4  1949    5.0         121
5  1949    6.0         135

In [22]:
df = df.dropna()

In [23]:
df = df[df["month"].notnull()]

In [24]:
print(df.head())
print(df.shape)

   year  month  passengers
0  1949    1.0         112
2  1949    3.0         132
3  1949    4.0         129
4  1949    5.0         121
5  1949    6.0         135
(132, 3)

In [25]:
df = df.dropna()

In [26]:
x = df[["year", "month"]]
y = df["passengers"]

In [27]:
# from sklearn.model_selection import train_test_split

# x_train, x_test, y_train, y_test = train_test_split(
#     x, y, test_size=0.2, random_state=42
# )

# model = LinearRegression()
# model.fit(x_train, y_train)

In [28]:
# Import Libraries
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load Dataset
df = sns.load_dataset("flights")

# First 5 Rows
print(df.head())

# Last 5 Rows
print(df.tail())

# Dataset Shape
print("Shape:", df.shape)

# Column Names
print(df.columns)

# Data Types
print(df.dtypes)

# Dataset Info
print(df.info())

# Null Values
print(df.isnull().sum())

# Statistical Summary
print(df.describe())

# Unique Months
print(df["month"].unique())

# Unique Years
print(df["year"].unique())

# Display Dataset
print(df)

   year month  passengers
0  1949   Jan         112
1  1949   Feb         118
2  1949   Mar         132
3  1949   Apr         129
4  1949   May         121
     year month  passengers
139  1960   Aug         606
140  1960   Sep         508
141  1960   Oct         461
142  1960   Nov         390
143  1960   Dec         432
Shape: (144, 3)
Index(['year', 'month', 'passengers'], dtype='str')
year             int64
month         category
passengers       int64
dtype: object
<class 'pandas.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   year        144 non-null    int64
 1   month       144 non-null    category
 2   passengers  144 non-null    int64
dtypes: category(1), int64(2)
memory usage: 2.9 KB
None
year          0
month         0
passengers    0
dtype: int64
              year  passengers
count   144.000000  144.000000
mean   1954.500000  280.298611
std       3.464102  119.966317
min    1949.000000  104.000000
25%    1951.750000  180.000000
50%    1954.500000  265.500000
75%    1957.250000  360.500000
max    1960.000000  622.000000
['Jan', 'Feb', 'Mar', 'Apr', 'May', ..., 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
Length: 12
Categories (12, str): ['Jan', 'Feb', 'Mar', 'Apr', ..., 'Sep', 'Oct', 'Nov', 'Dec']
[1949 1950 1951 1952 1953 1954 1955 1956 1957 1958 1959 1960]
     year month  passengers
0    1949   Jan         112
1    1949   Feb         118
2    1949   Mar         132
3    1949   Apr         129
4    1949   May         121
..    ...   ...         ...
139  1960   Aug         606
140  1960   Sep         508
141  1960   Oct         461
142  1960   Nov         390
143  1960   Dec         432

[144 rows x 3 columns]

In [29]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import r2_score

# Load Dataset
df = sns.load_dataset("flights")

# Encode Month
le = LabelEncoder()
df["month"] = le.fit_transform(df["month"])

# Features and Target
X = df[["year", "month"]]
y = df["passengers"]

# Train Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Train Model
model = LinearRegression()
model.fit(X_train, y_train)

# Prediction
y_pred = model.predict(X_test)

# Accuracy
print("R2 Score:", r2_score(y_test, y_pred))

print("Coefficient:", model.coef_)
print("Intercept:", model.intercept_)

R2 Score: 0.8411230149448436
Coefficient: [32.90322536 -1.19034799]
Intercept: -64020.8317835495

In [30]:
comparison=pd.DataFrame({
    "Actual":y_test.values,
    "Predicted":y_pred
})
comparison = pd.DataFrame({"Actual": y_test.values, "Predicted": y_pred})

comparison["Absolute error"] = abs(comparison["Actual"] - comparison["Predicted"])

print(comparison)

    Actual   Predicted  Absolute error
0      359  391.779996       32.779996
1      170  139.267325       30.732675
2      237  294.260667       57.260667
3      301  367.209206       66.209206
4      237  226.073521       10.926479
5      115  135.696281       20.696281
6      417  464.728534       47.728534
7      264  264.928486        0.928486
8      302  266.118834       35.881166
9      170  134.505933       35.494067
10     235  239.167349        4.167349
11     364  299.022059       64.977941
12     271  327.163893       56.163893
13     391  465.918882       74.918882
14     355  361.257466        6.257466
15     234  262.547790       28.547790
16     163  173.360898       10.360898
17     229  260.167094       31.167094
18     472  429.444613       42.555387
19     233  301.402755       68.402755
20     118  105.173751       12.826249
21     337  401.302779       64.302779
22     362  395.351040       33.351040
23     435  396.541388       38.458612
24     272  237.977001       34.022999
25     191  194.360643        3.360643
26     119   95.650967       23.349033
27     121   98.031663       22.968337
28     178  165.028462       12.971538